"""empty message

Revision ID: 9854e5a6c2ff
Revises: 93a84973ac6a
Create Date: 2017-03-09 17:14:02.240653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9854e5a6c2ff'
down_revision = '93a84973ac6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('honors_id', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_users_honors_id'), 'users', ['honors_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_honors_id'), table_name='users')
    op.drop_column('users', 'honors_id')
    # ### end Alembic commands ###
